services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  placapix:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: placapix
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/postgres
    ports:
      - "80:80"
    networks:
      - db
    volumes:
      - ./placapix:/app
    depends_on:
      db:
        condition: service_healthy

networks:
  db:
    driver: bridge

volumes:
  db:
